name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: "17"
        cache: "gradle"

    - name: Cache Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      with:
        cmdline-tools-version: "10406996"
        packages: |-
          platform-tools
          platforms;android-34
          build-tools;34.0.0

    - name: Make Gradle wrapper executable
      run: chmod +x ./gradlew

    - name: Build Debug APK
      run: ./gradlew :app:assembleDebug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: ZeinFlow-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
        retention-days: 14